### PR TITLE
allow embeds in before_scenario + fix embed of error messages

### PR DESCRIPTION
**Pull request by fpokryvk**

### CODE REVIEW

**Comment by bittner** [comment]
Following up on https://github.com/behave-contrib/behave-html-formatter/issues/14:

Would it make sense to add this contribution to [behave-contrib/behave-html-formatter](https://github.com/behave-contrib/behave-html-formatter/)?

**Comment by fpokryvk** [comment]
@bittner I created this MR because in our team (Desktop/NetworkManager QE) we are using before_scenario and after_scenario a lot, and we usually were not able to see what exactly happened in HTML report and had to look at STDOUT report of the behave. So, this small change allows embed to HTML (even if it sometimes embeds to non traditional place, but at least embedded information is shown and not lost).

**Comment by fpokryvk** [comment]
@bittner I communicated with @schidlo that this is main repo now (I did not know about the change). I will fork this and will make PR here. Sorry, for the mess.

**Comment by bittner** [comment]
Thanks for the clarification!

@schidlo Can you add a disclaimer to the top for your project's README, saying that the copy at @behave-contrib is now the official repository? Ideally, you also archive this repository, to make things crystal-clear. – You do have full maintainer access at [behave-contrib/behave-html-formatter](https://github.com/behave-contrib/behave-html-formatter/), don't you?

**Pull request merged**
